### ISSUE TITLE
Appleri privateda saxlayib deploy etmek

### ISSUE THREAD

**Issue by orgnu** [thisisyusub/thisisyusub.github.io#1]
Yeqin ki bilirsiz, her ehtimala yazmaq istedim.

Bunun ucun netlify istifade ede bilersiz. Netlifyin cox ozelliyi var, pulsuzdur hem de 😄 

[maraqli ola biler](https://medium.com/@D10100111001/flutter-web-netlify-continuous-deployment-the-right-way-in-2-minutes-f2ed4a4fcbf7)

**Comment by thisisyusub** [comment]
I know. It is just for test.
